name: build-founder

on:
  push:
    branches:
      - main
    paths:
      - founder/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('build-founder-{0}', github.head_ref || 'main') }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: {submodules: recursive}
      - uses: ructions/toolchain@v2
        with: {toolchain: stable}
      - run: make -C founder test-vectorize-selected
      - run: make -C founder test-name-selected
      - run: make -C founder test-vectorize
      - run: make -C founder test-name
      - run: make -C founder test-rasterize-selected
