name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || 'main' }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: {submodules: true}
      - run: make configure
        shell: bash
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make tests-draw
        shell: bash
      - run: make tests-scan
        shell: bash

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {submodules: true}
      - run: make configure
        shell: bash
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make tests-draw
        shell: bash
      - run: make tests-scan
        shell: bash
