name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('build-founder-{0}', github.head_ref || 'main') }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile=minimal --component clippy --component rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: {submodules: recursive}
      - run: rustup toolchain install stable --profile=minimal
      - run: make -C founder test-name-internal
      - run: make -C founder test-rasterize-internal
      - run: make -C founder test-vectorize-internal
      - run: make -C founder test-name-external
      - run: make -C founder test-vectorize-external
