name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || 'main' }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make setup
        shell: bash
      - uses: actions-rs/cargo@v1
        with: {command: run --bin scan -- --path tests/fixtures/google-fonts}

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make setup
        shell: bash
      - uses: actions-rs/cargo@v1
        with: {command: run --bin scan -- --path tests/fixtures/google-fonts}
