name: build-founder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || 'main' }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with: {submodules: true}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make -C founder tests-draw-selected
        shell: bash
      - run: make -C founder tests-name-selected
        shell: bash
      - run: make -C founder tests-sign-selected
        shell: bash
      - run: make -C founder tests-scan
        shell: bash
      - run: make -C founder tests-sign
        shell: bash

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with: {submodules: true}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make -C founder tests-draw-selected
        shell: bash
      - run: make -C founder tests-name-selected
        shell: bash
      - run: make -C founder tests-sign-selected
        shell: bash
      - run: make -C founder tests-scan
        shell: bash
      - run: make -C founder tests-sign
        shell: bash
