name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('build-founder-{0}', github.head_ref || 'main') }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile=minimal --component clippy --component rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {submodules: recursive}
      - run: rustup toolchain install stable --profile=minimal

      - run: make test-internal-features
      - run: make test-internal-names
      - run: make test-internal-rasterize
      - run: make test-internal-vectorize
      - run: make test-external-names
      - run: make test-external-vectorize
