name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - explorer/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('build-{0}', github.head_ref || 'main') }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with: {submodules: true}
      - uses: ructions/toolchain@v2
        with: {toolchain: stable, components: "clippy, rustfmt"}
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: {submodules: true}
      - uses: ructions/toolchain@v2
        with: {toolchain: stable}
      - run: cargo test
