name: build-founder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ format('build-founder-{0}', github.head_ref || 'main') }}
  cancel-in-progress: true

jobs:
  configuration:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v35
        with: {files_ignore: explorer/**}

  macos:
    needs: configuration
    if: ${{ needs.configuration.changed }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: {submodules: recursive}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make -C founder tests-draw-selected
      - run: make -C founder tests-name-selected
      - run: make -C founder tests-sign-selected
      - run: make -C founder tests-scan
      - run: make -C founder tests-sign

  ubuntu:
    needs: configuration
    if: ${{ needs.configuration.changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {submodules: recursive}
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: make -C founder tests-draw-selected
      - run: make -C founder tests-name-selected
      - run: make -C founder tests-sign-selected
      - run: make -C founder tests-scan
      - run: make -C founder tests-sign
